apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: week1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/haniazahid531/week1-microservices-local-cluster-frontend:latest
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL
              value: http://backend-service:8080
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: week1
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 8081
      targetPort: http
  type: ClusterIP
